### ISSUE TITLE
unit tests: create environment handler fixture

### ISSUE THREAD

**Issue by david-caro** [inspirehep/hepcrawl#113]
Currently the unit tests that depend on the pipeline module to generate the records, are implicitly depending on the test `tests/unit/test_pipelines.py::test_prepare_payload` to set some env variables for them before running (meaning that if you try to run them without running that one first, they will fail).

We should refactor it and add a fixture that properly sets up and cleans up the env variables (we might want mock.patch).

**Comment by spirosdelviniotis** [comment]
* If run, for e.g. the `test_arxiv_all.py` test separately from the whole unit tests suite, it passes because it doesn't checks the entire record. So the `SCRAPY_JOB` env variable is asserted only at the new introduced unit test of WSP #112. 
* Question: Can we solve the issue by adding only one fixture at the `tests/unit/test_pipelines.py` or should we add it at the `tests/unit/__init__.py` file for now (and later at https://github.com/inspirehep/hepcrawl/pull/104 we move it to `hepcrawl/testlib/utils.py`)?

**Comment by david-caro** [comment]
The fixtures don't go inside the testlib module, they go in the conftest.py files in the test dirs (that's how pytest organizes them).So the fixture should go in a new file `tests/conftest.py` that will picked up (if I'm not mistaken) by all the tests and render it available.

**Comment by spirosdelviniotis** [comment]
* You are right! With the `tests/conftest.py` we are fine! 
* Last question: What about the other spiders that they use the pipelines output but not the env variable?
  Should I pass the fixture also there or it's not necessary ?
