### ISSUE TITLE
Use material whenever possible

### ISSUE THREAD

**Issue by michamos** [inspirehep/hepcrawl#128]
The `arXiv` spider harvests only preprints, so there should be `material: preprint` in the output JSON whenever there is a `material` field.
For the publishers, if we know for sure whether are harvesting an article/erratum/addendum/reprint, the `material` should be set appropriately as well.

**Comment by spirosdelviniotis** [comment]
@michamos @kaplun I have a question about:

> The arXiv spider harvests only preprints, so there should be material: preprint in the output JSON whenever there is a material field.

Just harvested some `arXiv` records but I can't see any `material` field or something similar.
Can you give us an example of `arXiv` record with `material` field? That would be useful.

**Comment by kaplun** [comment]
@spirosdelviniotis, what @michamos meant is that it's the responsibility of the arXiv crawler to always write in the output the corresponding `material -> preprint`, because that's always the only valid value for arXiv.

**Comment by spirosdelviniotis** [comment]
@kaplun Thanks!
So, will convert the `arXiv` spider to populate the `material` field with `preprint`.

**Comment by kaplun** [comment]
So discussing IRL with @spirosdelviniotis looks like the `material` subfields are present in:
* `copyright`
* `dois`
* `license`
* `persistent_identifiers`
* `publication_info`

Now thinking in detail. If we have `copyright` and `license`, we should add `preprint` as `material` (because these are referring to the copy from arXiv). For `dois` and `publication_info`, we should put `publication` because for the time being the doi is provided by the user to refer to the corresponding published version. The day in which arXiv will start to mint their own DOIs they will surely expose them in a sensible way and it will be clear that that DOI will refer to the `preprint`.

For `persistent_identifier` that's currently not filled from arXiv I am guessing.

**Comment by david-caro** [comment]
DOI and copyright are not being filled up either.

**Comment by kaplun** [comment]
You mean arXiv does not provide this information? Are you sure?

**Comment by spirosdelviniotis** [comment]
@kaplun just checked that `arXiv` provide us `doi` and not `copyright`.

**Comment by kaplun** [comment]
:+1: and for future reference: here's all and only fields currently exposed by arXiv:
https://arxiv.org/OAI/arXivRaw.xsd
